<header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
        
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="brand"><?php echo $this->getLogoAlt() ?></a>
    
            <?php echo $this->getChildHtml('topLinks') ?>
            <?php echo $this->getChildHtml('store_language') ?>
    
            <?php echo $this->getChildHtml('topContainer'); ?>
        </div>
    </div>
</header>
<?php echo $this->getChildHtml('topMenu') ?>
