<meta property="og:site_name" content="Resposiv Shop"/>
<meta property="og:street-address" content="Resposiv Str."/>
<meta property="og:locality" content="Resposivtown"/>
<meta property="og:postal-code:" content="10000"/>
<meta property="og:country-name:" content="Resposiv Land"/>
<meta property="og:phone_number" content="00490891000000"/>
<meta property="og:latitude" content="10.00000"/>
<meta property="og:longitude" content="10.00000"/>
<meta property="fb:admins" content="1000000000"/>

<?php
$_product = Mage::registry('current_product');
if ($_product) {
    ?>
    <meta property="og:title" content="<?php echo $this->getTitle() ?>" />
    <meta property="og:type" content="product" />
    <meta property="og:url" content="<?php echo $_product->getProductUrl() ?>" />
    <meta property="og:image" content="<?php echo str_replace('https://', 'http://', Mage::helper('catalog/image')->init($_product, 'image')->resize(300)) ?>" />
    <meta property="og:description" content="<?php echo strip_tags($_product->getShortDescription()) ?>" />
    <?php
}
?>

<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
